import { Building2, Check, Copy, CreditCard, KeyRound, LockKeyhole, Mail, Plus, ShieldCheck, Trash2, UsersRound } from 'lucide-react';
import { useState } from 'react';
import { useAuth, useToast } from '@/components/providers';
import { Badge, Button, Card, Field, Switch } from '@/components/ui';

export function SettingsPage() {
  const { session } = useAuth(); const { pushToast } = useToast(); const [section, setSection] = useState('workspace'); const [copied, setCopied] = useState(false); const [masking, setMasking] = useState(true);
  const nav = [{ id: 'workspace', label: 'Workspace', icon: Building2 }, { id: 'team', label: 'Team members', icon: UsersRound }, { id: 'api', label: 'API keys', icon: KeyRound }, { id: 'security', label: 'Security', icon: ShieldCheck }, { id: 'billing', label: 'Billing', icon: CreditCard }];
  return <div className="page settings-page"><div className="page-heading"><h2>Workspace settings</h2><p>Manage your organization, team, and developer access.</p></div><div className="settings-layout"><nav>{nav.map(({ id, label, icon: Icon }) => <button key={id} className={section === id ? 'is-active' : ''} onClick={() => setSection(id)}><Icon/>{label}</button>)}</nav><div className="workspace-settings-content">
    {section === 'workspace' ? <Card className="workspace-card"><div className="settings-section__heading"><span><Building2/></span><div><h3>Workspace profile</h3><p>Information shown to everyone in your workspace.</p></div></div><div className="settings-section__body"><div className="workspace-logo">N<button>Change logo</button></div><div className="two-fields"><Field label="Workspace name"><input defaultValue="Northstar Workspace"/></Field><Field label="Workspace slug"><div className="prefix-input"><span>app.northstar.ai/</span><input defaultValue="northstar"/></div></Field></div><Button onClick={() => pushToast('Workspace updated')}>Save changes</Button></div></Card> : null}
    {section === 'team' ? <Card className="workspace-card"><div className="settings-section__heading"><span><UsersRound/></span><div><h3>Team members</h3><p>Invite teammates and control workspace access.</p></div><Button icon={Plus}>Invite member</Button></div><div className="member-list"><div><span className="mini-avatar">{session?.user.name.charAt(0).toUpperCase()}</span><span><strong>{session?.user.name}</strong><small>{session?.user.email}</small></span><Badge tone="purple">Owner</Badge></div><div><span className="mini-avatar">A</span><span><strong>Alex Morgan</strong><small>alex@example.com</small></span><Badge>Admin</Badge></div></div></Card> : null}
    {section === 'api' ? <Card className="workspace-card"><div className="settings-section__heading"><span><KeyRound/></span><div><h3>API keys</h3><p>Authenticate server-side requests. Never expose keys in browser code.</p></div><Button icon={Plus}>Create secret key</Button></div><div className="api-key-row"><span><strong>Production</strong><small>Created Aug 12 · last used 2 minutes ago</small></span><code>nsk_live_••••••••••7f2a</code><button className="icon-button" onClick={() => { setCopied(true); window.setTimeout(() => setCopied(false), 1200); }} aria-label="Copy key ID">{copied ? <Check/> : <Copy/>}</button><button className="icon-button danger-hover" aria-label="Revoke key"><Trash2/></button></div><div className="security-callout"><LockKeyhole/><p>Secret keys are only shown once at creation. Store them in a secrets manager.</p></div></Card> : null}
    {section === 'security' ? <Card className="workspace-card"><div className="settings-section__heading"><span><ShieldCheck/></span><div><h3>Security & privacy</h3><p>Workspace-wide protection and access policies.</p></div></div><div className="settings-section__body"><Switch label="Sensitive data masking" description="Redact credentials, payment card details, and government IDs from logs." checked={masking} onChange={setMasking}/><Switch label="Require multi-factor authentication" description="Require every teammate to secure their account with a second factor." checked={false} onChange={() => undefined}/><Switch label="Weekly security digest" description="Email owners about unusual access and configuration changes." checked onChange={() => undefined}/><Field label="Security contact"><div className="icon-input"><Mail/><input defaultValue={session?.user.email}/></div></Field><Button onClick={() => pushToast('Security settings saved')}>Save changes</Button></div></Card> : null}
    {section === 'billing' ? <Card className="workspace-card"><div className="settings-section__heading"><span><CreditCard/></span><div><h3>Plan & billing</h3><p>Usage, invoices, and payment details.</p></div><Badge tone="brand">Growth plan</Badge></div><div className="plan-summary"><div><small>Current monthly usage</small><strong>1,892 / 5,000 conversations</strong><span><i style={{ width: '38%' }}/></span></div><Button variant="secondary">Manage billing</Button></div></Card> : null}
  </div></div></div>;
}
