import { Archive, Bot, CheckCircle2, ChevronDown, CircleAlert, Clock3, ExternalLink, Filter, Inbox, Mail, MessageCircle, MoreHorizontal, Search, Send, Smile, Sparkles, UserRound } from 'lucide-react';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useToast } from '@/components/providers';
import { Badge, Button, EmptyState, PageLoader } from '@/components/ui';
import { api } from '@/lib/api';
import { relativeTime } from '@/lib/format';
import { useApi } from '@/lib/use-api';
import type { Conversation, ConversationState } from '@/types';

export function ConversationsPage() {
  const result = useApi(() => api.conversations.list()); const [params, setParams] = useSearchParams(); const { pushToast } = useToast();
  const [search, setSearch] = useState(''); const [filter, setFilter] = useState<'all' | ConversationState>('all'); const [reply, setReply] = useState(''); const [sending, setSending] = useState(false);
  const filtered = useMemo(() => result.data?.items.filter((item) => (filter === 'all' || item.state === filter) && `${item.visitorName} ${item.preview}`.toLowerCase().includes(search.toLowerCase())) ?? [], [result.data, filter, search]);
  const selectedId = params.get('selected') ?? filtered[0]?.id; const selected = result.data?.items.find((item) => item.id === selectedId) ?? null;
  useEffect(() => { if (!params.get('selected') && filtered[0]) setParams({ selected: filtered[0].id }, { replace: true }); }, [filtered, params, setParams]);
  const setState = async (state: ConversationState) => { if (!selected) return; await api.conversations.updateState(selected.id, state); pushToast(state === 'resolved' ? 'Conversation resolved' : `Conversation marked ${state}`); result.reload(); };
  const submitReply = async (event: FormEvent) => { event.preventDefault(); if (!selected || !reply.trim() || sending) return; setSending(true); try { await api.conversations.reply(selected.id, reply.trim()); setReply(''); await result.reload(); pushToast('Reply sent'); } catch { pushToast('Reply could not be sent', 'error'); } finally { setSending(false); } };
  if (result.loading && !result.data) return <PageLoader />;
  return <div className="inbox-page">
    <section className={`conversation-list-panel ${selected ? 'has-selection' : ''}`}>
      <div className="inbox-title"><div><h2>Conversations</h2><Badge tone="brand">{result.data?.items.reduce((sum, item) => sum + item.unread, 0) ?? 0} new</Badge></div><button className="icon-button" aria-label="Conversation actions"><MoreHorizontal /></button></div>
      <div className="inbox-tools"><div className="search-box"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search conversations" /></div><div className="filter-select"><Filter /><select value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)} aria-label="Filter conversations"><option value="all">All</option><option value="open">Open</option><option value="escalated">Escalated</option><option value="resolved">Resolved</option></select><ChevronDown /></div></div>
      <div className="conversation-items">{filtered.map((conversation) => <button key={conversation.id} className={`conversation-item ${conversation.id === selectedId ? 'is-active' : ''}`} onClick={() => setParams({ selected: conversation.id })}><span className="mini-avatar">{conversation.visitorName.charAt(0)}</span><span className="conversation-item__copy"><span><strong>{conversation.visitorName}</strong><time>{relativeTime(conversation.updatedAt)}</time></span><small>{conversation.preview}</small><span className="conversation-item__tags"><Badge tone={conversation.state === 'escalated' ? 'danger' : conversation.state === 'resolved' ? 'neutral' : 'brand'}>{conversation.state}</Badge><em className={`sentiment sentiment--${conversation.sentiment}`}>{conversation.sentiment}</em></span></span>{conversation.unread ? <i className="unread-count">{conversation.unread}</i> : null}</button>)}</div>
      {!filtered.length ? <EmptyState icon={Inbox} title="No conversations here" description="Try another search or status filter." /> : null}
    </section>
    {selected ? <ConversationDetail conversation={selected} reply={reply} setReply={setReply} submitReply={submitReply} setState={setState} onBack={() => setParams({})} sending={sending} /> : <div className="conversation-empty"><MessageCircle /><h3>Select a conversation</h3><p>Read the full context, step in, or mark it resolved.</p></div>}
  </div>;
}

function ConversationDetail({ conversation, reply, setReply, submitReply, setState, onBack, sending }: { conversation: Conversation; reply: string; setReply: (value: string) => void; submitReply: (event: FormEvent) => void; setState: (state: ConversationState) => Promise<void>; onBack: () => void; sending: boolean }) {
  return <section className="conversation-detail">
    <header className="conversation-detail__header"><button className="mobile-back" onClick={onBack}>←</button><span className="mini-avatar mini-avatar--lg">{conversation.visitorName.charAt(0)}</span><div><h3>{conversation.visitorName}</h3><p><i className="status-dot status-dot--success" /> Active now · {conversation.channel}</p></div><div className="conversation-actions"><Button variant="secondary" size="sm" icon={Archive}>Archive</Button>{conversation.state !== 'resolved' ? <Button size="sm" icon={CheckCircle2} onClick={() => void setState('resolved')}>Resolve</Button> : <Button variant="secondary" size="sm" onClick={() => void setState('open')}>Reopen</Button>}</div></header>
    <div className="conversation-layout"><div className="conversation-thread"><div className="thread-notice"><Sparkles /> <span><strong>{conversation.state === 'escalated' ? 'Human attention requested' : 'Northstar handled this conversation'}</strong><small>The complete AI context is available below.</small></span></div><div className="message-day"><span>{new Date(conversation.startedAt).toLocaleDateString('en', { month: 'long', day: 'numeric' })}</span></div>
      {conversation.messages.map((message) => <div className={`inbox-message inbox-message--${message.role}`} key={message.id}>{message.role === 'user' ? <span className="message-avatar message-avatar--visitor">{conversation.visitorName.charAt(0)}</span> : <span className="message-avatar"><>{message.role === 'agent' ? <UserRound /> : <Sparkles />}</></span>}<div><span className="message-author">{message.role === 'user' ? conversation.visitorName : message.role === 'agent' ? 'You' : 'Northstar AI'} <time>{new Date(message.createdAt).toLocaleTimeString('en', { hour: 'numeric', minute: '2-digit' })}</time></span><div className="message-bubble">{message.content}</div>{message.citations?.map((citation) => <button className="citation-chip" key={citation.title}><ExternalLink />{citation.title}</button>)}</div></div>)}
    </div><form className="human-composer" onSubmit={(event) => void submitReply(event)}><textarea value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Reply as a teammate…" rows={2} disabled={sending} onKeyDown={(event) => { if ((event.ctrlKey || event.metaKey) && event.key === 'Enter') event.currentTarget.form?.requestSubmit(); }} /><div><span><button type="button" aria-label="Insert emoji"><Smile /></button><small>⌘ Enter to send</small></span><Button size="sm" icon={Send} disabled={!reply.trim() || sending}>{sending ? 'Sending…' : 'Send'}</Button></div></form></div>
    <aside className="visitor-panel"><div className="visitor-profile"><span className="mini-avatar mini-avatar--xl">{conversation.visitorName.charAt(0)}</span><h3>{conversation.visitorName}</h3><Badge tone={conversation.sentiment === 'positive' ? 'success' : conversation.sentiment === 'negative' ? 'danger' : 'neutral'}>{conversation.sentiment} sentiment</Badge></div><dl><div><dt><Mail /> Email</dt><dd>{conversation.visitorEmail ?? 'Not provided'}</dd></div><div><dt><Bot /> Agent</dt><dd>{conversation.agentId === 'agent-sales' ? 'Sales Concierge' : 'Northstar Guide'}</dd></div><div><dt><MessageCircle /> Channel</dt><dd className="capitalize">{conversation.channel}</dd></div><div><dt><Clock3 /> Started</dt><dd>{relativeTime(conversation.startedAt)}</dd></div><div><dt><CircleAlert /> Status</dt><dd className="capitalize">{conversation.state}</dd></div></dl><div className="conversation-summary"><strong><Sparkles /> AI summary</strong><p>{conversation.preview} The visitor may benefit from a short, direct follow-up.</p></div></aside>
  </section>;
}
